import type { ServicePageProps } from "@/components/sections/service-page";

type ServiceKey = "visa-services" | "travel-insurance" | "hotel-booking" | "flight-booking" | "transportation";

const commonFaqs = (name: string) => [
  { id: "s1", question: `How much does ${name.toLowerCase()} cost?`, answer: "Pricing depends on your specific requirements. Share your details and we'll give you a transparent, all-inclusive quote with no hidden fees." },
  { id: "s2", question: "How long does it take?", answer: "Most requests are processed within 24–72 hours. Time-sensitive requests can be fast-tracked — just let us know your deadline." },
  { id: "s3", question: "Is this available for international trips?", answer: "Yes, we support both domestic and international travel across 320+ destinations worldwide." },
  { id: "s4", question: "Can I bundle this with a tour package?", answer: "Absolutely. Bundling services with a package often unlocks better rates and a single, seamless point of contact." },
];

export const servicesData: Record<ServiceKey, ServicePageProps> = {
  "visa-services": {
    eyebrow: "Travel Services",
    title: "Visa Services",
    description: "End-to-end visa assistance so you can travel without the paperwork headache.",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=2000&q=80",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Visa Services" }],
    intro: "Visa applications are confusing, time-consuming and unforgiving of mistakes. Our dedicated visa desk handles the entire process — from figuring out which visa you need to preparing flawless documentation and booking your appointment.",
    features: [
      { icon: "FileCheck", title: "Document checklist", description: "A personalised list so you submit exactly what's required — nothing missing, nothing extra." },
      { icon: "CalendarCheck", title: "Appointment booking", description: "We secure the earliest available embassy or VFS slots for you." },
      { icon: "ShieldCheck", title: "Application review", description: "Expert eyes check every form before submission to avoid rejections." },
      { icon: "Globe", title: "180+ countries", description: "Tourist, business and transit visas for destinations across the globe." },
      { icon: "Clock", title: "Fast-track options", description: "Urgent travel? We expedite where embassies allow." },
      { icon: "Headphones", title: "Status updates", description: "Track your application with proactive updates at every stage." },
    ],
    steps: [
      { title: "Share your trip", description: "Tell us your destination, dates and passport details." },
      { title: "We prepare docs", description: "Get a tailored checklist and filled-in application forms." },
      { title: "Submit & track", description: "Attend your appointment; we monitor progress." },
      { title: "Visa in hand", description: "Collect your visa and pack your bags." },
    ],
    benefits: ["Personalised, destination-specific guidance", "Reduced risk of rejection", "Appointment scheduling handled", "Transparent pricing, no surprises"],
    faqs: commonFaqs("Visa Services"),
    ctaLabel: "Apply for a visa",
  },
  "travel-insurance": {
    eyebrow: "Travel Services",
    title: "Travel Insurance",
    description: "Comprehensive cover for medical emergencies, cancellations, baggage and more.",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=2000&q=80",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Travel Insurance" }],
    intro: "The best trips are the worry-free ones. Our travel insurance plans protect you against the unexpected — from a missed flight to a medical emergency abroad — so a small mishap never becomes a big problem.",
    features: [
      { icon: "HeartPulse", title: "Medical cover", description: "Emergency medical, hospitalisation and evacuation up to high limits." },
      { icon: "CalendarX", title: "Trip cancellation", description: "Recover non-refundable costs if you have to cancel or cut short." },
      { icon: "Luggage", title: "Baggage protection", description: "Cover for lost, delayed or damaged baggage." },
      { icon: "PlaneLanding", title: "Flight delays", description: "Compensation for significant delays and missed connections." },
      { icon: "Globe2", title: "Worldwide validity", description: "Single-trip and annual multi-trip plans covering the globe." },
      { icon: "Headphones", title: "24/7 assistance", description: "Round-the-clock emergency helpline wherever you are." },
    ],
    benefits: ["Cover from just a few hundred rupees per trip", "Instant policy issuance", "Cashless hospital network abroad", "Family and senior-citizen plans"],
    faqs: commonFaqs("Travel Insurance"),
    ctaLabel: "Get insured",
  },
  "hotel-booking": {
    eyebrow: "Travel Services",
    title: "Hotel Booking",
    description: "Handpicked stays at the best rates — from boutique gems to five-star luxury.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=2000&q=80",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Hotel Booking" }],
    intro: "We don't just book hotels — we recommend the right one. Leveraging years of on-the-ground experience and partnerships with the world's best properties, we match you to stays that fit your style, budget and location perfectly.",
    features: [
      { icon: "BedDouble", title: "Curated selection", description: "Only properties we'd stay in ourselves make the cut." },
      { icon: "BadgeIndianRupee", title: "Best-rate access", description: "Negotiated rates and perks you won't find on public sites." },
      { icon: "MapPin", title: "Perfect locations", description: "Stays chosen for convenience, safety and the best views." },
      { icon: "Sparkles", title: "Complimentary perks", description: "Upgrades, late checkout and breakfast where available." },
      { icon: "Users", title: "Groups & families", description: "Connecting rooms, suites and villas for any group size." },
      { icon: "ShieldCheck", title: "Flexible options", description: "Free-cancellation rates and secure, protected bookings." },
    ],
    benefits: ["Access to member-only rates", "Personal recommendations, not endless lists", "One point of contact for changes", "Loyalty perks and upgrades"],
    faqs: commonFaqs("Hotel Booking"),
    ctaLabel: "Find a hotel",
  },
  "flight-booking": {
    eyebrow: "Travel Services",
    title: "Flight Booking",
    description: "The best routes and fares across every airline, booked and managed for you.",
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=2000&q=80",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Flight Booking" }],
    intro: "Finding the right flight is about more than the cheapest fare — it's routes, timings, layovers and airline reliability. We compare across every airline to build the smartest itinerary, then manage it for you end to end.",
    features: [
      { icon: "Plane", title: "All airlines", description: "Full-service and low-cost carriers compared side by side." },
      { icon: "Route", title: "Smart routing", description: "Optimal connections that save time, money and hassle." },
      { icon: "Tag", title: "Fare deals", description: "Access to special fares, corporate deals and bundles." },
      { icon: "RefreshCw", title: "Changes handled", description: "Reschedules, cancellations and refunds managed for you." },
      { icon: "Users", title: "Group fares", description: "Special group booking rates for 10+ travellers." },
      { icon: "Headphones", title: "Disruption support", description: "We rebook and reroute if flights are delayed or cancelled." },
    ],
    benefits: ["One team for flights + hotels + tours", "Proactive delay and disruption support", "Corporate and group fare access", "No hidden convenience fees"],
    faqs: commonFaqs("Flight Booking"),
    ctaLabel: "Book a flight",
  },
  transportation: {
    eyebrow: "Travel Services",
    title: "Transportation",
    description: "Airport transfers, private cars and coaches — comfortable, safe and on time.",
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=2000&q=80",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Transportation" }],
    intro: "Getting around should be the easy part. From the moment you land to your final drop-off, we arrange reliable, well-maintained vehicles with professional drivers so every journey between the highlights is smooth and stress-free.",
    features: [
      { icon: "PlaneLanding", title: "Airport transfers", description: "Meet-and-greet pickups and drop-offs, flight-tracked." },
      { icon: "Car", title: "Private cars", description: "Sedans, SUVs and luxury vehicles with expert local drivers." },
      { icon: "Bus", title: "Coaches & vans", description: "Comfortable group transport for tours and events." },
      { icon: "Clock", title: "Always on time", description: "Punctual, tracked and coordinated with your itinerary." },
      { icon: "ShieldCheck", title: "Safety first", description: "Vetted drivers, insured and well-maintained vehicles." },
      { icon: "MapPinned", title: "Anywhere you go", description: "Point-to-point, hourly hire or full-day at your service." },
    ],
    benefits: ["Flight-tracked airport pickups", "Professional, English-speaking drivers", "Transparent, fixed pricing", "Available across all our destinations"],
    faqs: commonFaqs("Transportation"),
    ctaLabel: "Arrange transport",
  },
};
